### ISSUE TITLE
弱弱的问下，这个相对于本地maven的优势是什么？

### ISSUE THREAD

**Issue by Sanjay-F** [JackyAndroid/GreenBeanPods#1]
我理解，本地仓库也可以传源码，然后直接调试，同时也不同升版本号。
如果要接入你这个，需要改依赖脚本，统一要有一堆的开关控制，也怕哪天忘了改同步就提交上去了。

**Comment by JackyAndroid** [comment]
恩，简单，ignore PodsSpec.groovy文件

**Comment by Sanjay-F** [comment]
> 恩，简单，ignore PodsSpec.groovy文件

那相对于本地maven库呢？

**Comment by JackyAndroid** [comment]
使用本地maven当然可以实现，这个是为了方便替换线上maven为本地源码依赖

**Comment by Sanjay-F** [comment]
> 使用本地maven当然可以实现，这个是为了方便替换线上maven为本地源码依赖

你看，我是这么理解的，如果我们是为了能替换线上maven，那就是有源码的库。
按照你项目的说法，这些都是自己的业务组件，那么其实这个项目工程你也是拿得到。
1. 如果是别人管理的业务：
如果是线上maven有bug，那么是对应的组件同学去改bug，我们一般不会自己去改别人业务。
对应的同学用maven本地依赖，那么这个就是相当于直接类似于在同个工程下修改，而且也是支持增量build，然后更新本地maven。

2. 如果是自己管理的业务模块：
那么自己也有对应的代码，也可以直接修改。

所以对于你说的方便替换线上maven为本地源码依赖的问题，我感觉是否真的有必要？

你开头提出的问题： “  程中升级maven仓库版本号，再验证问题是否修复，以及功能是否满足需求。”

那我理解，潜台词的意思是：“这个远处maven的代码，这个就是自己项目的代码，也是本地有人维护的“

所以我觉得mavenLocal完全可以解决了，你也觉得使用本地maven当然可以实现。

所以我就有点疑惑，不知道你能否指出点别的具体场景？可以更好match需要这样做的？

**Comment by JackyAndroid** [comment]
恩，简单来说。
我维护了一个maven仓库，这个仓库被几个工程线上依赖，我现在需要发布一个功能，而且需要到工程中去验证，本地源码肯定可以，但是需要改几个地方：1. 注释所有线上依赖的地方 2. 配置本地源码路径。
那能不能只修改一个开关就可以实现？可以，就是用插件实现切源码，这个就是实际需求点。

美团外卖在文章中也指出，如果本地修改会有两个问题：
1. build.gradle改动频繁，如果开发人员不小心push上去了，将会造成各种冲突。
2. 当业务库越来越多时，这种改动的成本就越来越大了。

**Comment by JackyAndroid** [comment]
no response.

**Comment by Sanjay-F** [comment]
> 那能不能只修改一个开关就可以实现？可以，就是用插件实现切源码，这个就是实际需求点。

谢谢你诚心的回复，还是有点小小的疑问想了解下
对于你提到的改依赖和配置本地源码路径方式，我理解是否是这样
eg：

`implementation 'com.android.support:appcompat-v7:' + "${rootProject.ext.support_version}"
`
1. 注释所有线上依赖的地方
现在需要到脚本改这个版本号support_version。

// 2. 配置本地源码路径。
然后同时在依赖的仓库修改来源
```
 repositories {
        mavenLocal()
        maven { 
            url "别的仓库地址"
        }
}
```
 
不过我理解，这个是可以不修改的，我本地发布的版本号完全可以和线上的一致，因此就不用改了

然后仓库问题，对于mavenLocal()地址是固定的本地路径即不需要写，而且repositories是顺序查找，如果mavenLocal没有，就去拉线上的，那么也就无所谓影响？就算提交也无所谓，别人本地不会编对应的包。push上去也没什么问题。

因为我这边也有类似组件库的版本老修改同步，一开始也想做点什么来改进，但我觉得用mavenLocal就可以简单的解决，看到你这本想接入，但又觉得好像不用啊，没改进什么，所以很疑惑?

你觉得呢？

**Comment by JackyAndroid** [comment]
首先，插件实现的原理和你描述的是不一样的。
简单原理见：http://t.cn/Etj57p4
插件的实现不是用mavenLocal替换线上maven，而是使用include project方式替换线上依赖。

然后，使用mavenLocal的方式依赖的还是aar，还是要走发布--验证流程，而不是直接源码调试。

**Comment by Sanjay-F** [comment]
> 首先，插件实现的原理和你描述的是不一样的。
> 简单原理见：http://t.cn/Etj57p4
> 插件的实现不是用mavenLocal替换线上maven，而是使用include project方式替换线上依赖。
> 
> 然后，使用mavenLocal的方式依赖的还是aar，还是要走发布--验证流程，而不是直接源码调试。

帮你说的1,2,3三篇文章都看完，我想目前项目遇到的问题是这样的。

1. 你的工程里面是直接包含业务代码的
![image](https://user-images.githubusercontent.com/8078089/52026178-dfd6a980-2541-11e9-88d2-34e6b236bcc8.png)
然后项目间互相通过`implementation project(':yourBizLibrary')`这样的方式来依赖的


2. 到了发布时候，这些业务插件需要都换成线上依赖，类似这样的
`implementation 'com.android.support.constraint:constraint-layout:1.1.3'`

3. 调试时候，老需要切换include project这个东西，同时在setting.gradle也需要修改
这样切换很麻烦。

基于上面三个问题，所以弄了这个库是吗？

**Comment by JackyAndroid** [comment]
大概正确。
但是项目一般都是线上依赖，所以一般是这样：api ”xxx“，等需要调试时再切换为project方式。
这样做对线上的原有依赖无侵入性。

**Comment by shaobin0604** [comment]
赞同 @JackyAndroid 

相对于直接源码依赖调试，mavenLocal 还是繁琐了点。

关于将 maven 依赖替换成模块依赖，gradle 提供了 API https://docs.gradle.org/current/userguide/customizing_dependency_resolution_behavior.html#sec:dependency_substitution_rules

```groovy
configurations.all {
    resolutionStrategy.dependencySubstitution {
        substitute module("org.utils:api") because "we work with the unreleased development version" with project(":api")
        substitute module("org.utils:util:2.5") with project(":util")
    }
}
```

**Comment by JackyAndroid** [comment]
@shaobin0604 多谢，看到相应的gradle Api了。
还是有部分缺点，见原文：”Note that a project that is substituted must be included in the multi-project build (via settings.gradle). Dependency substitution rules take care of replacing the module dependency with the project dependency and wiring up any task dependencies, but do not implicitly include the project in the build.“

这种方式相对于之前的更简化了，之后我会做相应的更新，也欢迎你PR。

**Comment by shaobin0604** [comment]
🤝
