### ISSUE TITLE
引入了 却说找不到工程

### ISSUE THREAD

**Issue by haizhiyun** [JackyAndroid/GreenBeanPods#2]
引入 按照配置编写了 但是同步时报找不到工程，依赖的库是和app 在同一级目录

**Comment by haizhiyun** [comment]
import greenbean.pods.GreenBean

@groovy.transform.BaseScript GreenBean pods

/**
 * Dependency description file
 * <pre>
 * {@code
 * pod{
 * on_off //Module switch
 * name   //Module name
 * group  //Module group
 * path   //Module local path, only supports the project parent directory to expand downward
 * branch //Module repository branch, switch branches according to path
 * cmd //Command hook, executed before include
 * excludes //Module's online dependency name
 * buildTypes //Module build type
 * seeds //Submodules that the module depends on must match the name field of the submodule
 *}*}
 * </pre>
 */

// The following is an example. If you want to dynamically debug the online module named ‘greenbean-pods-plugin-test-module’ in the app module, first configure the following.
pod {
    on_off true
    name 'Firework' // 被依赖库的名称
    group 'XX.XX.Firework.xx'
    path 'aaa/bbb'
}

**Comment by JackyAndroid** [comment]
现在的配置是仓库应该在项目的同级别，可向下扩展
同一个工程为啥还需要插件去依赖，直接改为project就可以了

**Comment by haizhiyun** [comment]
我们的场景和描述的很像，之所要要把库工程引入app 同级目录，就是想为了 project依赖方便，测试完后，再注释掉 project ，改成maven依赖， 看看引入这个插件会不会更方便

**Comment by JackyAndroid** [comment]
恩 好的 明白了，之后我会新加一个绝对路径选项，满足路径问题

**Comment by JackyAndroid** [comment]
@haizhiyun 升级到003版本
添加了absPath绝对路径配置

把相应的pod配置改为如下：
pod {
    on_off true
    name 'greenbean-pods-plugin-test-module'
    group 'tech.jackywang'
    absPath '/Users/xxx/Downloads/test-module/library' // 模块在本机的绝对路径
}
