### ISSUE TITLE
由于依赖的maven的本地源码还依赖了项目本地的.gradle文件，会出现找不到字段问题

### ISSUE THREAD

**Issue by SuperXmx** [JackyAndroid/GreenBeanPods#3]
![image](https://user-images.githubusercontent.com/24268288/60378782-ad7e9900-9a5a-11e9-85d8-2b6f135a363e.png)
![image](https://user-images.githubusercontent.com/24268288/60378794-c2f3c300-9a5a-11e9-8251-209550bf5c70.png)

**Comment by JackyAndroid** [comment]
用project替换rootproject

**Comment by SuperXmx** [comment]
使用project会找不到，因为对应的.gradle是在项目的build.gradle  apply进来的

**Comment by JackyAndroid** [comment]
恩，我的意思是在单独的project下重新加载外部的.gradle文件，而不是在项目中使用rootproject。
使用插件依赖外部的module，rootproject环境是指向现在的工程，而不是源工程，使用module的project单独加载.gradle试下。

**Comment by JackyAndroid** [comment]
no-response
